/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartDeviceRouteImport } from './routes/start.device'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as MfaSetupIdVerifyRouteImport } from './routes/mfa/$setupId.verify'
import { Route as MfaSetupIdStartRouteImport } from './routes/mfa/$setupId.start'
import { Route as MfaChallengeChallengeIdVerifyRouteImport } from './routes/mfa/challenge.$challengeId.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartDeviceRoute = StartDeviceRouteImport.update({
  id: '/start/device',
  path: '/start/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupIdVerifyRoute = MfaSetupIdVerifyRouteImport.update({
  id: '/mfa/$setupId/verify',
  path: '/mfa/$setupId/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupIdStartRoute = MfaSetupIdStartRouteImport.update({
  id: '/mfa/$setupId/start',
  path: '/mfa/$setupId/start',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeChallengeIdVerifyRoute =
  MfaChallengeChallengeIdVerifyRouteImport.update({
    id: '/mfa/challenge/$challengeId/verify',
    path: '/mfa/challenge/$challengeId/verify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/success': typeof AuthSuccessRoute
  '/start/device': typeof StartDeviceRoute
  '/mfa/$setupId/start': typeof MfaSetupIdStartRoute
  '/mfa/$setupId/verify': typeof MfaSetupIdVerifyRoute
  '/mfa/challenge/$challengeId/verify': typeof MfaChallengeChallengeIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/success': typeof AuthSuccessRoute
  '/start/device': typeof StartDeviceRoute
  '/mfa/$setupId/start': typeof MfaSetupIdStartRoute
  '/mfa/$setupId/verify': typeof MfaSetupIdVerifyRoute
  '/mfa/challenge/$challengeId/verify': typeof MfaChallengeChallengeIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/success': typeof AuthSuccessRoute
  '/start/device': typeof StartDeviceRoute
  '/mfa/$setupId/start': typeof MfaSetupIdStartRoute
  '/mfa/$setupId/verify': typeof MfaSetupIdVerifyRoute
  '/mfa/challenge/$challengeId/verify': typeof MfaChallengeChallengeIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/success'
    | '/start/device'
    | '/mfa/$setupId/start'
    | '/mfa/$setupId/verify'
    | '/mfa/challenge/$challengeId/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/success'
    | '/start/device'
    | '/mfa/$setupId/start'
    | '/mfa/$setupId/verify'
    | '/mfa/challenge/$challengeId/verify'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/success'
    | '/start/device'
    | '/mfa/$setupId/start'
    | '/mfa/$setupId/verify'
    | '/mfa/challenge/$challengeId/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  StartDeviceRoute: typeof StartDeviceRoute
  MfaSetupIdStartRoute: typeof MfaSetupIdStartRoute
  MfaSetupIdVerifyRoute: typeof MfaSetupIdVerifyRoute
  MfaChallengeChallengeIdVerifyRoute: typeof MfaChallengeChallengeIdVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/device': {
      id: '/start/device'
      path: '/start/device'
      fullPath: '/start/device'
      preLoaderRoute: typeof StartDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/$setupId/verify': {
      id: '/mfa/$setupId/verify'
      path: '/mfa/$setupId/verify'
      fullPath: '/mfa/$setupId/verify'
      preLoaderRoute: typeof MfaSetupIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/$setupId/start': {
      id: '/mfa/$setupId/start'
      path: '/mfa/$setupId/start'
      fullPath: '/mfa/$setupId/start'
      preLoaderRoute: typeof MfaSetupIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/challenge/$challengeId/verify': {
      id: '/mfa/challenge/$challengeId/verify'
      path: '/mfa/challenge/$challengeId/verify'
      fullPath: '/mfa/challenge/$challengeId/verify'
      preLoaderRoute: typeof MfaChallengeChallengeIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  StartDeviceRoute: StartDeviceRoute,
  MfaSetupIdStartRoute: MfaSetupIdStartRoute,
  MfaSetupIdVerifyRoute: MfaSetupIdVerifyRoute,
  MfaChallengeChallengeIdVerifyRoute: MfaChallengeChallengeIdVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
